### ISSUE TITLE
Where is src code? Is it permission issue or not yet uploaded?

### ISSUE THREAD

**Issue by techduggu** [microsoft/SmartHotel360#2]

**Comment by npagare** [comment]
There are totally 5 solutions. One of them has high-level architecture docs. Others have code for each tier as explained in the architecture document.

Look for in the '<> Code' tab above and the locate following section. 
**SmartHotel360 Repos**
For this reference app scenario, we built several consumer and line-of-business apps and an Azure backend. You can find all SmartHotel360 repos in the following locations:
SmartHotel360 
Backend Services
Public Website
Mobile Apps
Sentiment Analysis - Coming soon!

**Comment by techduggu** [comment]
Got it!! Thanks!
