### ISSUE TITLE
There is no source code files available

### ISSUE THREAD

**Issue by shanojscp** [microsoft/SmartHotel360#3]
There is no source code files available

**Comment by eiximenis** [comment]
Hi!
Source code is in their own repos:

* [Backend](https://github.com/Microsoft/SmartHotel360-Azure-backend)
* [Xamarin](https://github.com/Microsoft/SmartHotel360-mobile-desktop-apps)
* [Public Web](https://github.com/Microsoft/SmartHotel360-public-web)

Each repo contains the source code and instructions how to build and run it :)

**Comment by shanojscp** [comment]
Thank you :)
