### ISSUE TITLE
Keynote video link should go directly to Scott Hanselman's section of the video

### ISSUE THREAD

**Issue by ghost** [microsoft/SmartHotel360#4]
In Readme.md I suggest updating the connect 2017(); keynote link to go directly to Scott Hanselman's portion of the video that covers smart hotel 360:
https://channel9.msdn.com/Events/Connect/2017/K100#time=52m54s

**Comment by dsanchezcr** [comment]
There are several demos of SmartHotel360 during the keynote that's why we are leaving the whole video. Thanks!
